apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
      - name: python-service
        image: 805974095975.dkr.ecr.us-west-2.amazonaws.com/kubernetes-test:3f25dfac35058656570e36509255b959b0c3e8ad
