apiVersion: v1
kind: Service
metadata:
  name: my-service-load-balancer
spec:
  type: LoadBalancer
  #ExternalName
  selector:
    app: python-service
  ports:
  - name: "http"
    port: 5000
    targetPort: 5000